//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int codigo_actividad { get; set; }
        public int codigo_recomendacion { get; set; }
        public int codigo_hallazgo { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public int codigo_plan_accion_version { get; set; }
        public int codigo_plan_accion { get; set; }
        public int numero_actividad { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public string clasificacion_informacion { get; set; }
    
        public virtual Hallazgo_Informe_Auditoria Hallazgo_Informe_Auditoria { get; set; }
        public virtual Recomendacion_Informe_Auditoria Recomendacion_Informe_Auditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Plan_Accion Plan_Accion { get; set; }
    }
}
