//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int codigo_alerta { get; set; }
        public int codigo_usuario { get; set; }
        public int codigo_evento { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<int> codigo_informe_auditoria { get; set; }
        public Nullable<int> codigo_informe_seguimiento { get; set; }
        public System.DateTime fecha_notificacion { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public string mensaje { get; set; }
        public int dias_por_vencer { get; set; }
        public bool estado { get; set; }
        public Nullable<System.DateTime> fecha_hora_lectura { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Informe_Seguimiento Informe_Seguimiento { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
