//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int codigo_auditoria { get; set; }
        public int codigo_usuario { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string modulo { get; set; }
        public string entidad { get; set; }
        public string componente { get; set; }
        public string tipo_sentencia { get; set; }
        public string llave { get; set; }
        public string valores_anteriores { get; set; }
        public string valores_actuales { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
