//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Eventos
    {
        public int codigo_bitacora_evento { get; set; }
        public int codigo_usuario { get; set; }
        public string navegador { get; set; }
        public string direccion_ip { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string tipo_evento { get; set; }
        public bool estado_evento { get; set; }
        public string mensaje_evento { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
