//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Errores
    {
        public int codigo_bitacora_error { get; set; }
        public Nullable<int> codigo_usuario { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string componente { get; set; }
        public string descripcion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
