//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidad()
        {
            this.Informe_Auditoria = new HashSet<Informe_Auditoria>();
            this.Entidad_Auditora = new HashSet<Entidad_Auditora>();
            this.Organigrama_Entidad_Relacion = new HashSet<Organigrama_Entidad_Relacion>();
            this.Solicitud_Enrolamiento = new HashSet<Solicitud_Enrolamiento>();
            this.Usuario_Entidad = new HashSet<Usuario_Entidad>();
        }
    
        public int codigo_entidad_version { get; set; }
        public int codigo_entidad { get; set; }
        public Nullable<int> codigo_sector { get; set; }
        public Nullable<int> codigo_tipo_asignacion_entidad { get; set; }
        public Nullable<int> codigo_clasificacion_entidad { get; set; }
        public Nullable<int> codigo_geografico { get; set; }
        public string nombre { get; set; }
        public string siglas { get; set; }
        public string correo_electronico { get; set; }
        public string sitio_web { get; set; }
        public string telefono { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public bool version_actual { get; set; }
        public Nullable<int> codigo_organigrama_seguimiento { get; set; }
        public Nullable<int> referencia_externa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria { get; set; }
        public virtual Clasificacion_Entidad Clasificacion_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad_Auditora> Entidad_Auditora { get; set; }
        public virtual Geografico Geografico { get; set; }
        public virtual Organigrama Organigrama { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Tipo_Asignacion_Entidad Tipo_Asignacion_Entidad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama_Entidad_Relacion> Organigrama_Entidad_Relacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Enrolamiento> Solicitud_Enrolamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Entidad> Usuario_Entidad { get; set; }
    }
}
