//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad_Auditora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidad_Auditora()
        {
            this.Informe_Auditoria = new HashSet<Informe_Auditoria>();
        }
    
        public int codigo_entidad_auditora { get; set; }
        public string nombre { get; set; }
        public int codigo_clase_entidad_auditora { get; set; }
        public Nullable<int> codigo_entidad_version { get; set; }
        public Nullable<int> codigo_entidad { get; set; }
        public string siglas { get; set; }
        public string correo_electronico { get; set; }
        public string sitio_web { get; set; }
        public string telefono { get; set; }
        public int estado { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria { get; set; }
        public virtual Clase_Entidad_Auditora Clase_Entidad_Auditora { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
