//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidencia_Seguimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evidencia_Seguimiento()
        {
            this.Enlace_Evidencia_Recomendacion = new HashSet<Enlace_Evidencia_Recomendacion>();
        }
    
        public int codigo_evidencia { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public int codigo_informe_seguimiento { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> referencia_documento { get; set; }
        public int tipo_evidencia { get; set; }
        public Nullable<System.DateTime> fecha_hora_carga { get; set; }
        public Nullable<int> codigo_usuario_carga { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        public virtual Informe_Seguimiento Informe_Seguimiento { get; set; }
    }
}
