//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo_Estado_Informe_Seguimiento
    {
        public int codigo_informe_seguimiento { get; set; }
        public int codigo_usuario { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string estado_anterior { get; set; }
        public string estado_actual { get; set; }
        public string comentario { get; set; }
    }
}
