//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo_Estado_Informe_Auditoria
    {
        public int codigo_informe_auditoria { get; set; }
        public int codigo_usuario { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int estado_anterior { get; set; }
        public int estado_actual { get; set; }
        public string comentario { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
