//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Evento
    {
        public int codigo_grupo { get; set; }
        public int codigo_evento { get; set; }
        public Nullable<int> escenario { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
