//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Bandeja
    {
        public int codigo_grupo { get; set; }
        public string fase { get; set; }
        public int bandeja { get; set; }
        public int predominancia { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
