//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hallazgo_Informe_Auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hallazgo_Informe_Auditoria()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Recomendacion_Informe_Auditoria = new HashSet<Recomendacion_Informe_Auditoria>();
            this.Recomendacion_Plan_Accion = new HashSet<Recomendacion_Plan_Accion>();
            this.Solicitud_Adenda_Plan_Accion_Actividad = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
        }
    
        public int codigo_hallazgo { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public int numero { get; set; }
        public string titulo { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Informe_Auditoria> Recomendacion_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
    }
}
