//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_Estado_Usuario_Externo
    {
        public int codigo_historico_estado_usuario_externo { get; set; }
        public int codigo_usuario { get; set; }
        public int codigo_estado_usuario_externo { get; set; }
        public Nullable<System.DateTime> fecha_hora_creacion { get; set; }
    
        public virtual Estado_Usuario_Externo Estado_Usuario_Externo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
