//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Seguimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informe_Seguimiento()
        {
            this.Notificacion = new HashSet<Notificacion>();
            this.Enlace_Evidencia_Recomendacion = new HashSet<Enlace_Evidencia_Recomendacion>();
            this.Entrevista_Informe_Seguimiento = new HashSet<Entrevista_Informe_Seguimiento>();
            this.Evidencia_Seguimiento = new HashSet<Evidencia_Seguimiento>();
            this.Alerta = new HashSet<Alerta>();
            this.Observacion_Informe_Seguimiento = new HashSet<Observacion_Informe_Seguimiento>();
            this.Presentacion_Evidencia = new HashSet<Presentacion_Evidencia>();
            this.Presentacion_Evidencia_Recomendacion = new HashSet<Presentacion_Evidencia_Recomendacion>();
            this.Seguimiento_Recomendacion = new HashSet<Seguimiento_Recomendacion>();
            this.Solicitud_Evidencia = new HashSet<Solicitud_Evidencia>();
            this.Solicitud_Evidencia_Recomendacion = new HashSet<Solicitud_Evidencia_Recomendacion>();
        }
    
        public int codigo_informe_seguimiento { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public string numero_informe_seguimiento { get; set; }
        public Nullable<int> codigo_usuario_supervisor { get; set; }
        public Nullable<int> tipo_informe_seguimiento { get; set; }
        public Nullable<int> numero_visita { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public bool estado { get; set; }
        public Nullable<int> instancia { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<bool> fue_impreso { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevista_Informe_Seguimiento> Entrevista_Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencia_Seguimiento> Evidencia_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Seguimiento> Observacion_Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia> Presentacion_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia_Recomendacion> Presentacion_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Recomendacion> Seguimiento_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia> Solicitud_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia_Recomendacion> Solicitud_Evidencia_Recomendacion { get; set; }
    }
}
