//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informe_Auditoria()
        {
            this.Hallazgo_Informe_Auditoria = new HashSet<Hallazgo_Informe_Auditoria>();
            this.Alerta = new HashSet<Alerta>();
            this.Asignacion_Supervisor_Informe = new HashSet<Asignacion_Supervisor_Informe>();
            this.Enlace_Evidencia_Recomendacion = new HashSet<Enlace_Evidencia_Recomendacion>();
            this.Evidencia_Seguimiento = new HashSet<Evidencia_Seguimiento>();
            this.Flujo_Estado_Informe_Auditoria = new HashSet<Flujo_Estado_Informe_Auditoria>();
            this.Informe_Seguimiento = new HashSet<Informe_Seguimiento>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Observacion_Informe_Auditoria = new HashSet<Observacion_Informe_Auditoria>();
            this.Plan_Accion = new HashSet<Plan_Accion>();
            this.Presentacion_Evidencia = new HashSet<Presentacion_Evidencia>();
            this.Presentacion_Evidencia_Recomendacion = new HashSet<Presentacion_Evidencia_Recomendacion>();
            this.Presentacion_Plan_Accion = new HashSet<Presentacion_Plan_Accion>();
            this.Seguimiento_Recomendacion = new HashSet<Seguimiento_Recomendacion>();
            this.Solicitud_Adenda_Plan_Accion = new HashSet<Solicitud_Adenda_Plan_Accion>();
            this.Solicitud_Evidencia = new HashSet<Solicitud_Evidencia>();
            this.Solicitud_Evidencia_Recomendacion = new HashSet<Solicitud_Evidencia_Recomendacion>();
            this.Solicitud_Prorroga = new HashSet<Solicitud_Prorroga>();
            this.Tipo_Auditoria_Informe_Auditoria = new HashSet<Tipo_Auditoria_Informe_Auditoria>();
        }
    
        public int codigo_informe_auditoria { get; set; }
        public string numero_informe { get; set; }
        public string numero_oficio_remision { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string tema { get; set; }
        public string rubro { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public int codigo_fuente_financiera { get; set; }
        public int codigo_entidad_auditora { get; set; }
        public Nullable<int> codigo_usuario_supervisor { get; set; }
        public Nullable<int> codigo_usuario_supervisor_seguimiento { get; set; }
        public Nullable<int> codigo_entidad_version { get; set; }
        public int codigo_entidad { get; set; }
        public int codigo_usuario_auditor { get; set; }
        public Nullable<int> codigo_geografico { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> codigo_organigrama { get; set; }
        public Nullable<int> instancia { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hallazgo_Informe_Auditoria> Hallazgo_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_Supervisor_Informe> Asignacion_Supervisor_Informe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencia_Seguimiento> Evidencia_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flujo_Estado_Informe_Auditoria> Flujo_Estado_Informe_Auditoria { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Entidad_Auditora Entidad_Auditora { get; set; }
        public virtual Estado_Proceso Estado_Proceso { get; set; }
        public virtual Fuente_Financiera Fuente_Financiera { get; set; }
        public virtual Geografico Geografico { get; set; }
        public virtual Organigrama Organigrama { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
        public virtual Usuario Usuario4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Seguimiento> Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Auditoria> Observacion_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Accion> Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia> Presentacion_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia_Recomendacion> Presentacion_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Plan_Accion> Presentacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Recomendacion> Seguimiento_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia> Solicitud_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia_Recomendacion> Solicitud_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Prorroga> Solicitud_Prorroga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Auditoria_Informe_Auditoria> Tipo_Auditoria_Informe_Auditoria { get; set; }
    }
}
