//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int codigo_menu { get; set; }
        public Nullable<int> codigo_ventana { get; set; }
        public Nullable<int> codigo_controlador_accion { get; set; }
        public Nullable<int> codigo_menu_padre { get; set; }
        public string titulo { get; set; }
        public string icono { get; set; }
        public Nullable<int> orden { get; set; }
        public string color { get; set; }
        public string url { get; set; }
        public Nullable<int> tipo_url { get; set; }
    
        public virtual Controlador_Accion Controlador_Accion { get; set; }
        public virtual Ventana Ventana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
