//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organigrama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organigrama()
        {
            this.Informe_Auditoria = new HashSet<Informe_Auditoria>();
            this.Entidad = new HashSet<Entidad>();
            this.Organigrama_Entidad_Relacion = new HashSet<Organigrama_Entidad_Relacion>();
            this.Organigrama_Entidad_Relacion1 = new HashSet<Organigrama_Entidad_Relacion>();
            this.Usuario_Organigrama = new HashSet<Usuario_Organigrama>();
        }
    
        public int codigo_organigrama { get; set; }
        public string descripcion { get; set; }
        public int codigo_nivel_organizacional { get; set; }
        public Nullable<int> codigo_organigrama_padre { get; set; }
        public int codigo_usuario_jefe { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad> Entidad { get; set; }
        public virtual Nivel_Organizacional Nivel_Organizacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama_Entidad_Relacion> Organigrama_Entidad_Relacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama_Entidad_Relacion> Organigrama_Entidad_Relacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Organigrama> Usuario_Organigrama { get; set; }
    }
}
