//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organigrama_Entidad_Relacion
    {
        public int codigo_organigrama_principal { get; set; }
        public string tipo_asignacion { get; set; }
        public Nullable<int> codigo_organigrama_segundario { get; set; }
        public Nullable<int> codigo_entidad_version { get; set; }
        public Nullable<int> codigo_entidad { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Organigrama Organigrama { get; set; }
        public virtual Organigrama Organigrama1 { get; set; }
    }
}
