//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int codigo_parametro { get; set; }
        public string nombre_parametro { get; set; }
        public string nombre_modulo { get; set; }
        public string valor { get; set; }
        public string descripcion { get; set; }
    }
}
