//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Accion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan_Accion()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Flujo_Estado_Plan_Accion = new HashSet<Flujo_Estado_Plan_Accion>();
            this.Recomendacion_Plan_Accion = new HashSet<Recomendacion_Plan_Accion>();
            this.Solicitud_Adenda_Plan_Accion_Actividad = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion = new HashSet<Solicitud_Adenda_Plan_Accion>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
        }
    
        public int codigo_plan_accion_version { get; set; }
        public int codigo_plan_accion { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public string numero_identidad_aprueba { get; set; }
        public string nombre_aprueba { get; set; }
        public string observacion_presentacion { get; set; }
        public string observacion_seguimiento { get; set; }
        public string observacion_aprobacion { get; set; }
        public int estado { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public bool version_actual { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Estado_Proceso Estado_Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flujo_Estado_Plan_Accion> Flujo_Estado_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
    }
}
