//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portlet_Definicion
    {
        public int codigo_portlet { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> orden_prioridad { get; set; }
        public string valor_parametro_1 { get; set; }
        public string valor_parametro_2 { get; set; }
        public string valor_parametro_3 { get; set; }
        public string valor_parametro_4 { get; set; }
        public string valor_parametro_5 { get; set; }
    
        public virtual Portlet Portlet { get; set; }
    }
}
