//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portlet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Portlet()
        {
            this.Portlet_Definicion = new HashSet<Portlet_Definicion>();
        }
    
        public int codigo_portlet { get; set; }
        public string descripcion { get; set; }
        public string subdescripcion { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public string tipo_portlet { get; set; }
        public string subtipo_portlet { get; set; }
        public string url_servicio { get; set; }
        public string color { get; set; }
        public string nombre_leyenda { get; set; }
        public string parametro_1 { get; set; }
        public string parametro_2 { get; set; }
        public string parametro_3 { get; set; }
        public string parametro_4 { get; set; }
        public string parametro_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portlet_Definicion> Portlet_Definicion { get; set; }
    }
}
