//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentacion_Evidencia
    {
        public int codigo_presentacion_evidencia { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public int codigo_informe_seguimiento { get; set; }
        public string numero_oficio { get; set; }
        public Nullable<System.DateTime> fecha_oficio { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<int> codigo_usuario_aprueba { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public int estado { get; set; }
        public string numero_identidad_recibe { get; set; }
        public string nombre_recibe { get; set; }
        public string cargo_recibe { get; set; }
        public string observacion { get; set; }
        public string observacion_presentacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Estado_Proceso Estado_Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Informe_Seguimiento Informe_Seguimiento { get; set; }
        public virtual Presentacion_Evidencia_Recomendacion Presentacion_Evidencia_Recomendacion { get; set; }
    }
}
