//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipients
    {
        public int Recipient_Id { get; set; }
        public int Email_Request_Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Recipient_Type { get; set; }
        public bool Sent { get; set; }
        public string Result_Message { get; set; }
        public Nullable<System.DateTime> Sent_At { get; set; }
    
        public virtual EmailRequests EmailRequests { get; set; }
    }
}
