//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomendacion_Informe_Auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recomendacion_Informe_Auditoria()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Enlace_Evidencia_Recomendacion = new HashSet<Enlace_Evidencia_Recomendacion>();
            this.Presentacion_Evidencia_Recomendacion = new HashSet<Presentacion_Evidencia_Recomendacion>();
            this.Recomendacion_Plan_Accion = new HashSet<Recomendacion_Plan_Accion>();
            this.Seguimiento_Recomendacion = new HashSet<Seguimiento_Recomendacion>();
            this.Solicitud_Adenda_Plan_Accion_Actividad = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
            this.Solicitud_Evidencia_Recomendacion = new HashSet<Solicitud_Evidencia_Recomendacion>();
        }
    
        public int codigo_recomendacion { get; set; }
        public int codigo_hallazgo { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public int codigo_tipo_recomendacion { get; set; }
        public int numero { get; set; }
        public int codigo_prioridad_recomendacion { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public string descripcion { get; set; }
        public string dirigido_a { get; set; }
        public int estado { get; set; }
        public Nullable<int> codigo_recomendacion_padre { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
    
        public virtual Hallazgo_Informe_Auditoria Hallazgo_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia_Recomendacion> Presentacion_Evidencia_Recomendacion { get; set; }
        public virtual Estado_Recomendacion Estado_Recomendacion { get; set; }
        public virtual Prioridad_Recomendacion Prioridad_Recomendacion { get; set; }
        public virtual Tipo_Recomendacion Tipo_Recomendacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Recomendacion> Seguimiento_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia_Recomendacion> Solicitud_Evidencia_Recomendacion { get; set; }
    }
}
