//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento_Recomendacion
    {
        public int codigo_informe_seguimiento { get; set; }
        public int codigo_recomendacion { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public int estado { get; set; }
        public string anexo { get; set; }
        public string observacion { get; set; }
        public string comentario { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<bool> es_heredado { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Recomendacion_Informe_Auditoria Recomendacion_Informe_Auditoria { get; set; }
        public virtual Estado_Recomendacion Estado_Recomendacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Informe_Seguimiento Informe_Seguimiento { get; set; }
    }
}
