//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Enrolamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud_Enrolamiento()
        {
            this.Solicitud_Enrolamiento_Detalle = new HashSet<Solicitud_Enrolamiento_Detalle>();
        }
    
        public int codigo_solicitud_enrolamiento { get; set; }
        public int codigo_entidad { get; set; }
        public int codigo_entidad_version { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public string enlace_documento { get; set; }
        public string numero_oficio { get; set; }
        public Nullable<System.DateTime> fecha_oficio { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string numero_identidad_entrega { get; set; }
        public string nombre_entrega { get; set; }
        public string cargo_entrega { get; set; }
        public string numero_identidad_recibe { get; set; }
        public string nombre_recibe { get; set; }
        public string cargo_recibe { get; set; }
        public string observacion { get; set; }
        public Nullable<int> codigo_usuario_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public string estado_solicitud_enrolamiento { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Enrolamiento_Detalle> Solicitud_Enrolamiento_Detalle { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
