//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Adenda_Plan_Accion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud_Adenda_Plan_Accion()
        {
            this.Solicitud_Adenda_Plan_Accion_Actividad = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
        }
    
        public int codigo_solicitud_adenda { get; set; }
        public int codigo_plan_accion_version { get; set; }
        public int codigo_plan_accion { get; set; }
        public int codigo_informe_auditoria { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public string numero_oficio { get; set; }
        public Nullable<System.DateTime> fecha_oficio { get; set; }
        public string numero_identidad_entrega { get; set; }
        public string nombre_entrega { get; set; }
        public string cargo_entrega { get; set; }
        public string numero_identidad_recibe { get; set; }
        public string nombre_recibe { get; set; }
        public string cargo_recibe { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<int> codigo_usuario_aprueba { get; set; }
        public string observacion_presentacion { get; set; }
        public string observacion_aprobacion { get; set; }
        public int estado { get; set; }
        public int codigo_usuario_creacion { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public Nullable<int> referencia_documento { get; set; }
    
        public virtual Informe_Auditoria Informe_Auditoria { get; set; }
        public virtual Estado_Proceso Estado_Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Plan_Accion Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
    }
}
