//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tsc_his_db_devEntities : DbContext
    {
        public tsc_his_db_devEntities()
            : base("name=tsc_his_db_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hallazgo_Informe_Auditoria> Hallazgo_Informe_Auditoria { get; set; }
        public virtual DbSet<Informe_Auditoria> Informe_Auditoria { get; set; }
        public virtual DbSet<Observacion_Informe_Auditoria> Observacion_Informe_Auditoria { get; set; }
        public virtual DbSet<Recomendacion_Informe_Auditoria> Recomendacion_Informe_Auditoria { get; set; }
        public virtual DbSet<Tipo_Auditoria_Informe_Auditoria> Tipo_Auditoria_Informe_Auditoria { get; set; }
        public virtual DbSet<Clase_Entidad_Auditora> Clase_Entidad_Auditora { get; set; }
        public virtual DbSet<Clasificacion_Entidad> Clasificacion_Entidad { get; set; }
        public virtual DbSet<Dias_Feriados> Dias_Feriados { get; set; }
        public virtual DbSet<Enlaces> Enlaces { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<Entidad_Auditora> Entidad_Auditora { get; set; }
        public virtual DbSet<Estado_Proceso> Estado_Proceso { get; set; }
        public virtual DbSet<Estado_Recomendacion> Estado_Recomendacion { get; set; }
        public virtual DbSet<Estado_Usuario_Externo> Estado_Usuario_Externo { get; set; }
        public virtual DbSet<Fuente_Financiera> Fuente_Financiera { get; set; }
        public virtual DbSet<Geografico> Geografico { get; set; }
        public virtual DbSet<Nivel_Organizacional> Nivel_Organizacional { get; set; }
        public virtual DbSet<Organigrama> Organigrama { get; set; }
        public virtual DbSet<Prioridad_Recomendacion> Prioridad_Recomendacion { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Tipo_Asignacion_Entidad> Tipo_Asignacion_Entidad { get; set; }
        public virtual DbSet<Tipo_Auditoria> Tipo_Auditoria { get; set; }
        public virtual DbSet<Tipo_Informe_Seguimiento> Tipo_Informe_Seguimiento { get; set; }
        public virtual DbSet<Tipo_Notificacion> Tipo_Notificacion { get; set; }
        public virtual DbSet<Tipo_Recomendacion> Tipo_Recomendacion { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<EmailRequests> EmailRequests { get; set; }
        public virtual DbSet<EmailTemplates> EmailTemplates { get; set; }
        public virtual DbSet<EmailTemplatesTypes> EmailTemplatesTypes { get; set; }
        public virtual DbSet<ErrorLogs> ErrorLogs { get; set; }
        public virtual DbSet<Recipients> Recipients { get; set; }
        public virtual DbSet<Bitacora_Errores> Bitacora_Errores { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Portlet> Portlet { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Bitacora_Eventos> Bitacora_Eventos { get; set; }
        public virtual DbSet<Codigo_Verificacion_Usuario> Codigo_Verificacion_Usuario { get; set; }
        public virtual DbSet<Control> Control { get; set; }
        public virtual DbSet<Control_Contexto> Control_Contexto { get; set; }
        public virtual DbSet<Controlador_Accion> Controlador_Accion { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Grupo_Evento> Grupo_Evento { get; set; }
        public virtual DbSet<Historico_Estado_Usuario_Externo> Historico_Estado_Usuario_Externo { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Solicitud_Enrolamiento> Solicitud_Enrolamiento { get; set; }
        public virtual DbSet<Solicitud_Enrolamiento_Detalle> Solicitud_Enrolamiento_Detalle { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Entidad> Usuario_Entidad { get; set; }
        public virtual DbSet<Usuario_Grupo> Usuario_Grupo { get; set; }
        public virtual DbSet<Usuario_Organigrama> Usuario_Organigrama { get; set; }
        public virtual DbSet<Ventana> Ventana { get; set; }
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Asignacion_Supervisor_Informe> Asignacion_Supervisor_Informe { get; set; }
        public virtual DbSet<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        public virtual DbSet<Entrevista_Informe_Seguimiento> Entrevista_Informe_Seguimiento { get; set; }
        public virtual DbSet<Evidencia_Seguimiento> Evidencia_Seguimiento { get; set; }
        public virtual DbSet<Informe_Seguimiento> Informe_Seguimiento { get; set; }
        public virtual DbSet<Observacion_Informe_Seguimiento> Observacion_Informe_Seguimiento { get; set; }
        public virtual DbSet<Plan_Accion> Plan_Accion { get; set; }
        public virtual DbSet<Presentacion_Evidencia> Presentacion_Evidencia { get; set; }
        public virtual DbSet<Presentacion_Evidencia_Recomendacion> Presentacion_Evidencia_Recomendacion { get; set; }
        public virtual DbSet<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion { get; set; }
        public virtual DbSet<Seguimiento_Recomendacion> Seguimiento_Recomendacion { get; set; }
        public virtual DbSet<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion { get; set; }
        public virtual DbSet<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        public virtual DbSet<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
        public virtual DbSet<Solicitud_Evidencia> Solicitud_Evidencia { get; set; }
        public virtual DbSet<Solicitud_Evidencia_Recomendacion> Solicitud_Evidencia_Recomendacion { get; set; }
        public virtual DbSet<Solicitud_Prorroga> Solicitud_Prorroga { get; set; }
        public virtual DbSet<Alerta> Alerta { get; set; }
        public virtual DbSet<Configuracion_Alerta> Configuracion_Alerta { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Mensaje_Aplicativo> Mensaje_Aplicativo { get; set; }
        public virtual DbSet<Mensaje_Correo> Mensaje_Correo { get; set; }
        public virtual DbSet<Flujo_Estado_Informe_Auditoria> Flujo_Estado_Informe_Auditoria { get; set; }
        public virtual DbSet<Portlet_Definicion> Portlet_Definicion { get; set; }
        public virtual DbSet<Grupo_Bandeja> Grupo_Bandeja { get; set; }
        public virtual DbSet<Organigrama_Entidad_Relacion> Organigrama_Entidad_Relacion { get; set; }
        public virtual DbSet<Flujo_Estado_Informe_Seguimiento> Flujo_Estado_Informe_Seguimiento { get; set; }
        public virtual DbSet<Flujo_Estado_Plan_Accion> Flujo_Estado_Plan_Accion { get; set; }
        public virtual DbSet<Presentacion_Plan_Accion> Presentacion_Plan_Accion { get; set; }
        public virtual DbSet<Despacho_Correo_Alertas> Despacho_Correo_Alertas { get; set; }
    }
}
