//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Hallazgo_Informe_Auditoria = new HashSet<Hallazgo_Informe_Auditoria>();
            this.Hallazgo_Informe_Auditoria1 = new HashSet<Hallazgo_Informe_Auditoria>();
            this.Informe_Auditoria = new HashSet<Informe_Auditoria>();
            this.Informe_Auditoria1 = new HashSet<Informe_Auditoria>();
            this.Informe_Auditoria2 = new HashSet<Informe_Auditoria>();
            this.Informe_Auditoria3 = new HashSet<Informe_Auditoria>();
            this.Informe_Auditoria4 = new HashSet<Informe_Auditoria>();
            this.Observacion_Informe_Auditoria = new HashSet<Observacion_Informe_Auditoria>();
            this.Observacion_Informe_Auditoria1 = new HashSet<Observacion_Informe_Auditoria>();
            this.Observacion_Informe_Auditoria2 = new HashSet<Observacion_Informe_Auditoria>();
            this.Recomendacion_Informe_Auditoria = new HashSet<Recomendacion_Informe_Auditoria>();
            this.Recomendacion_Informe_Auditoria1 = new HashSet<Recomendacion_Informe_Auditoria>();
            this.Clase_Entidad_Auditora = new HashSet<Clase_Entidad_Auditora>();
            this.Clase_Entidad_Auditora1 = new HashSet<Clase_Entidad_Auditora>();
            this.Clasificacion_Entidad = new HashSet<Clasificacion_Entidad>();
            this.Clasificacion_Entidad1 = new HashSet<Clasificacion_Entidad>();
            this.Enlaces = new HashSet<Enlaces>();
            this.Enlaces1 = new HashSet<Enlaces>();
            this.Entidad = new HashSet<Entidad>();
            this.Entidad1 = new HashSet<Entidad>();
            this.Entidad_Auditora = new HashSet<Entidad_Auditora>();
            this.Entidad_Auditora1 = new HashSet<Entidad_Auditora>();
            this.Estado_Proceso = new HashSet<Estado_Proceso>();
            this.Estado_Proceso1 = new HashSet<Estado_Proceso>();
            this.Estado_Recomendacion = new HashSet<Estado_Recomendacion>();
            this.Estado_Recomendacion1 = new HashSet<Estado_Recomendacion>();
            this.Fuente_Financiera = new HashSet<Fuente_Financiera>();
            this.Fuente_Financiera1 = new HashSet<Fuente_Financiera>();
            this.Geografico = new HashSet<Geografico>();
            this.Geografico1 = new HashSet<Geografico>();
            this.Nivel_Organizacional = new HashSet<Nivel_Organizacional>();
            this.Nivel_Organizacional1 = new HashSet<Nivel_Organizacional>();
            this.Organigrama = new HashSet<Organigrama>();
            this.Organigrama1 = new HashSet<Organigrama>();
            this.Organigrama2 = new HashSet<Organigrama>();
            this.Prioridad_Recomendacion = new HashSet<Prioridad_Recomendacion>();
            this.Prioridad_Recomendacion1 = new HashSet<Prioridad_Recomendacion>();
            this.Sector = new HashSet<Sector>();
            this.Sector1 = new HashSet<Sector>();
            this.Tipo_Asignacion_Entidad = new HashSet<Tipo_Asignacion_Entidad>();
            this.Tipo_Asignacion_Entidad1 = new HashSet<Tipo_Asignacion_Entidad>();
            this.Tipo_Auditoria = new HashSet<Tipo_Auditoria>();
            this.Tipo_Auditoria1 = new HashSet<Tipo_Auditoria>();
            this.Tipo_Informe_Seguimiento = new HashSet<Tipo_Informe_Seguimiento>();
            this.Tipo_Informe_Seguimiento1 = new HashSet<Tipo_Informe_Seguimiento>();
            this.Tipo_Notificacion = new HashSet<Tipo_Notificacion>();
            this.Tipo_Notificacion1 = new HashSet<Tipo_Notificacion>();
            this.Tipo_Recomendacion = new HashSet<Tipo_Recomendacion>();
            this.Tipo_Recomendacion1 = new HashSet<Tipo_Recomendacion>();
            this.Bitacora_Errores = new HashSet<Bitacora_Errores>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Notificacion1 = new HashSet<Notificacion>();
            this.Auditoria = new HashSet<Auditoria>();
            this.Bitacora_Eventos = new HashSet<Bitacora_Eventos>();
            this.Codigo_Verificacion_Usuario = new HashSet<Codigo_Verificacion_Usuario>();
            this.Grupo = new HashSet<Grupo>();
            this.Grupo1 = new HashSet<Grupo>();
            this.Historico_Estado_Usuario_Externo = new HashSet<Historico_Estado_Usuario_Externo>();
            this.Solicitud_Enrolamiento = new HashSet<Solicitud_Enrolamiento>();
            this.Solicitud_Enrolamiento1 = new HashSet<Solicitud_Enrolamiento>();
            this.Solicitud_Enrolamiento_Detalle = new HashSet<Solicitud_Enrolamiento_Detalle>();
            this.Actividad = new HashSet<Actividad>();
            this.Actividad1 = new HashSet<Actividad>();
            this.Alerta = new HashSet<Alerta>();
            this.Asignacion_Supervisor_Informe = new HashSet<Asignacion_Supervisor_Informe>();
            this.Asignacion_Supervisor_Informe1 = new HashSet<Asignacion_Supervisor_Informe>();
            this.Asignacion_Supervisor_Informe2 = new HashSet<Asignacion_Supervisor_Informe>();
            this.Entrevista_Informe_Seguimiento = new HashSet<Entrevista_Informe_Seguimiento>();
            this.Entrevista_Informe_Seguimiento1 = new HashSet<Entrevista_Informe_Seguimiento>();
            this.Enlace_Evidencia_Recomendacion = new HashSet<Enlace_Evidencia_Recomendacion>();
            this.Enlace_Evidencia_Recomendacion1 = new HashSet<Enlace_Evidencia_Recomendacion>();
            this.Evidencia_Seguimiento = new HashSet<Evidencia_Seguimiento>();
            this.Evidencia_Seguimiento1 = new HashSet<Evidencia_Seguimiento>();
            this.Evidencia_Seguimiento2 = new HashSet<Evidencia_Seguimiento>();
            this.Flujo_Estado_Informe_Auditoria = new HashSet<Flujo_Estado_Informe_Auditoria>();
            this.Flujo_Estado_Plan_Accion = new HashSet<Flujo_Estado_Plan_Accion>();
            this.Informe_Seguimiento = new HashSet<Informe_Seguimiento>();
            this.Informe_Seguimiento1 = new HashSet<Informe_Seguimiento>();
            this.Informe_Seguimiento2 = new HashSet<Informe_Seguimiento>();
            this.Mensaje_Aplicativo = new HashSet<Mensaje_Aplicativo>();
            this.Mensaje_Correo = new HashSet<Mensaje_Correo>();
            this.Observacion_Informe_Seguimiento = new HashSet<Observacion_Informe_Seguimiento>();
            this.Observacion_Informe_Seguimiento1 = new HashSet<Observacion_Informe_Seguimiento>();
            this.Observacion_Informe_Seguimiento2 = new HashSet<Observacion_Informe_Seguimiento>();
            this.Plan_Accion = new HashSet<Plan_Accion>();
            this.Plan_Accion1 = new HashSet<Plan_Accion>();
            this.Presentacion_Evidencia = new HashSet<Presentacion_Evidencia>();
            this.Presentacion_Evidencia1 = new HashSet<Presentacion_Evidencia>();
            this.Presentacion_Evidencia2 = new HashSet<Presentacion_Evidencia>();
            this.Presentacion_Plan_Accion = new HashSet<Presentacion_Plan_Accion>();
            this.Presentacion_Plan_Accion1 = new HashSet<Presentacion_Plan_Accion>();
            this.Recomendacion_Plan_Accion = new HashSet<Recomendacion_Plan_Accion>();
            this.Recomendacion_Plan_Accion1 = new HashSet<Recomendacion_Plan_Accion>();
            this.Seguimiento_Recomendacion = new HashSet<Seguimiento_Recomendacion>();
            this.Seguimiento_Recomendacion1 = new HashSet<Seguimiento_Recomendacion>();
            this.Solicitud_Adenda_Plan_Accion_Actividad = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion_Actividad1 = new HashSet<Solicitud_Adenda_Plan_Accion_Actividad>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
            this.Solicitud_Adenda_Plan_Accion_Recomendacion1 = new HashSet<Solicitud_Adenda_Plan_Accion_Recomendacion>();
            this.Solicitud_Adenda_Plan_Accion = new HashSet<Solicitud_Adenda_Plan_Accion>();
            this.Solicitud_Adenda_Plan_Accion1 = new HashSet<Solicitud_Adenda_Plan_Accion>();
            this.Solicitud_Adenda_Plan_Accion2 = new HashSet<Solicitud_Adenda_Plan_Accion>();
            this.Solicitud_Evidencia = new HashSet<Solicitud_Evidencia>();
            this.Solicitud_Evidencia1 = new HashSet<Solicitud_Evidencia>();
            this.Solicitud_Evidencia2 = new HashSet<Solicitud_Evidencia>();
            this.Solicitud_Prorroga = new HashSet<Solicitud_Prorroga>();
            this.Solicitud_Prorroga1 = new HashSet<Solicitud_Prorroga>();
            this.Solicitud_Prorroga2 = new HashSet<Solicitud_Prorroga>();
            this.Usuario_Entidad = new HashSet<Usuario_Entidad>();
            this.Usuario_Entidad1 = new HashSet<Usuario_Entidad>();
            this.Usuario_Entidad2 = new HashSet<Usuario_Entidad>();
            this.Usuario_Grupo = new HashSet<Usuario_Grupo>();
            this.Usuario_Grupo1 = new HashSet<Usuario_Grupo>();
            this.Usuario_Grupo2 = new HashSet<Usuario_Grupo>();
            this.Usuario_Organigrama = new HashSet<Usuario_Organigrama>();
            this.Usuario_Organigrama1 = new HashSet<Usuario_Organigrama>();
            this.Usuario_Organigrama2 = new HashSet<Usuario_Organigrama>();
            this.Menu = new HashSet<Menu>();
        }
    
        public int codigo_usuario { get; set; }
        public string usuario1 { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string numero_identidad { get; set; }
        public string clave { get; set; }
        public bool estado { get; set; }
        public string correo_electronico { get; set; }
        public System.DateTime fecha_hora_creacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_modificacion { get; set; }
        public System.DateTime fecha_hora_activacion { get; set; }
        public Nullable<System.DateTime> fecha_hora_inactivacion { get; set; }
        public bool requiere_cambio_clave { get; set; }
        public Nullable<int> codigo_usuario_creacion { get; set; }
        public Nullable<int> codigo_usuario_modificacion { get; set; }
        public Nullable<bool> es_usuario_externo { get; set; }
        public Nullable<int> codigo_solicitud_enrolamiento_detalle { get; set; }
        public string referencia_externa_cargo { get; set; }
        public Nullable<int> codigo_estado_usuario_externo { get; set; }
        public string ruta_encriptada_generada { get; set; }
        public Nullable<System.DateTime> fecha_hora_primera_autenticacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hallazgo_Informe_Auditoria> Hallazgo_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hallazgo_Informe_Auditoria> Hallazgo_Informe_Auditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Auditoria> Informe_Auditoria4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Auditoria> Observacion_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Auditoria> Observacion_Informe_Auditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Auditoria> Observacion_Informe_Auditoria2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Informe_Auditoria> Recomendacion_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Informe_Auditoria> Recomendacion_Informe_Auditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase_Entidad_Auditora> Clase_Entidad_Auditora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase_Entidad_Auditora> Clase_Entidad_Auditora1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasificacion_Entidad> Clasificacion_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasificacion_Entidad> Clasificacion_Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlaces> Enlaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlaces> Enlaces1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad> Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad> Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad_Auditora> Entidad_Auditora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entidad_Auditora> Entidad_Auditora1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Proceso> Estado_Proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Proceso> Estado_Proceso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Recomendacion> Estado_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estado_Recomendacion> Estado_Recomendacion1 { get; set; }
        public virtual Estado_Usuario_Externo Estado_Usuario_Externo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fuente_Financiera> Fuente_Financiera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fuente_Financiera> Fuente_Financiera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geografico> Geografico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geografico> Geografico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nivel_Organizacional> Nivel_Organizacional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nivel_Organizacional> Nivel_Organizacional1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama> Organigrama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama> Organigrama1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organigrama> Organigrama2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prioridad_Recomendacion> Prioridad_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prioridad_Recomendacion> Prioridad_Recomendacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sector> Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sector> Sector1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Asignacion_Entidad> Tipo_Asignacion_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Asignacion_Entidad> Tipo_Asignacion_Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Auditoria> Tipo_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Auditoria> Tipo_Auditoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Informe_Seguimiento> Tipo_Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Informe_Seguimiento> Tipo_Informe_Seguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Notificacion> Tipo_Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Notificacion> Tipo_Notificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Recomendacion> Tipo_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_Recomendacion> Tipo_Recomendacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora_Errores> Bitacora_Errores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora_Eventos> Bitacora_Eventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigo_Verificacion_Usuario> Codigo_Verificacion_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo> Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo> Grupo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico_Estado_Usuario_Externo> Historico_Estado_Usuario_Externo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Enrolamiento> Solicitud_Enrolamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Enrolamiento> Solicitud_Enrolamiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Enrolamiento_Detalle> Solicitud_Enrolamiento_Detalle { get; set; }
        public virtual Solicitud_Enrolamiento_Detalle Solicitud_Enrolamiento_Detalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_Supervisor_Informe> Asignacion_Supervisor_Informe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_Supervisor_Informe> Asignacion_Supervisor_Informe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignacion_Supervisor_Informe> Asignacion_Supervisor_Informe2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevista_Informe_Seguimiento> Entrevista_Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevista_Informe_Seguimiento> Entrevista_Informe_Seguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enlace_Evidencia_Recomendacion> Enlace_Evidencia_Recomendacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencia_Seguimiento> Evidencia_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencia_Seguimiento> Evidencia_Seguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencia_Seguimiento> Evidencia_Seguimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flujo_Estado_Informe_Auditoria> Flujo_Estado_Informe_Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flujo_Estado_Plan_Accion> Flujo_Estado_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Seguimiento> Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Seguimiento> Informe_Seguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informe_Seguimiento> Informe_Seguimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje_Aplicativo> Mensaje_Aplicativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje_Correo> Mensaje_Correo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Seguimiento> Observacion_Informe_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Seguimiento> Observacion_Informe_Seguimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion_Informe_Seguimiento> Observacion_Informe_Seguimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Accion> Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Accion> Plan_Accion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia> Presentacion_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia> Presentacion_Evidencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Evidencia> Presentacion_Evidencia2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Plan_Accion> Presentacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentacion_Plan_Accion> Presentacion_Plan_Accion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacion_Plan_Accion> Recomendacion_Plan_Accion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Recomendacion> Seguimiento_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Recomendacion> Seguimiento_Recomendacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Actividad> Solicitud_Adenda_Plan_Accion_Actividad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion_Recomendacion> Solicitud_Adenda_Plan_Accion_Recomendacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Adenda_Plan_Accion> Solicitud_Adenda_Plan_Accion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia> Solicitud_Evidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia> Solicitud_Evidencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Evidencia> Solicitud_Evidencia2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Prorroga> Solicitud_Prorroga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Prorroga> Solicitud_Prorroga1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Prorroga> Solicitud_Prorroga2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Entidad> Usuario_Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Entidad> Usuario_Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Entidad> Usuario_Entidad2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Grupo> Usuario_Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Grupo> Usuario_Grupo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Grupo> Usuario_Grupo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Organigrama> Usuario_Organigrama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Organigrama> Usuario_Organigrama1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Organigrama> Usuario_Organigrama2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
